DEF_HELPER_1(aarch64_update_task, void, env)
DEF_HELPER_1(aarch64_update_current_task, void, env)
DEF_HELPER_1(amd64_update_current_task, void, env)
DEF_HELPER_1(armhf_update_current_task, void, env)
DEF_HELPER_1(i386_update_current_task, void, env)
DEF_HELPER_1(m68k_update_current_task, void, env)
DEF_HELPER_1(mips64_update_current_task, void, env)
DEF_HELPER_1(ppc_update_current_task, void, env)
DEF_HELPER_1(ppc64_update_current_task, void, env)
DEF_HELPER_1(riscv64_update_current_task, void, env)
DEF_HELPER_1(s390x_update_current_task, void, env)
DEF_HELPER_1(check_pc, void, env)
DEF_HELPER_2(x_ray_insert_hook, void, env, i64)